# Generated by Django 4.1.3 on 2024-01-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlphabettApp', '0004_remove_product_photos_product_image_delete_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_color', models.CharField(max_length=50)),
                ('product_image', models.ImageField(upload_to='photos/')),
                ('product_buying_price', models.IntegerField()),
                ('product_selling_price', models.IntegerField()),
                ('product_gender', models.CharField(choices=[('ladies', 'LADIES'), ('male', 'MALE')], max_length=10)),
                ('product_stock', models.IntegerField()),
                ('product_likes', models.IntegerField()),
            ],
        ),
    ]
