# Generated by Django 5.0 on 2024-04-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlphabettApp', '0005_watches'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAppliances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_image', models.ImageField(upload_to='photos/')),
                ('product_buying_price', models.IntegerField()),
                ('product_selling_price', models.IntegerField()),
                ('product_category', models.CharField(choices=[('kitchen-ware', 'KITCHENWARE'), ('utensils', 'UTENSILS'), ('kitchen-appliances', 'KITCHEN APPLIANCES')], max_length=20)),
                ('product_stock', models.IntegerField()),
                ('product_likes', models.IntegerField()),
            ],
        ),
    ]
