# Generated by Django 5.0 on 2024-05-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlphabettApp', '0007_alter_homeappliances_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeappliances',
            name='product_image',
            field=models.ImageField(upload_to='photos/home_appliances'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='photos/shoes'),
        ),
        migrations.AlterField(
            model_name='watches',
            name='product_image',
            field=models.ImageField(upload_to='photos/watches'),
        ),
    ]
